// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import {
  getApiV1AdminLogsCronByIdResponseTransformer,
  getApiV1AdminLogsCronResponseTransformer,
  getApiV1AdminLogsSendlogByIdResponseTransformer,
  getApiV1AdminLogsSendlogResponseTransformer,
  getApiV1AdminSecurityIncidentsByIdResponseTransformer,
  getApiV1AdminSecurityIncidentsResponseTransformer,
  getApiV1EventsByIdResponseTransformer,
  getApiV1EventsResponseTransformer,
  getApiV1GroupsByGroupSlugAdminMembersResponseTransformer,
  getApiV1GroupsByGroupSlugAdminSettingsResponseTransformer,
  getApiV1GroupsByGroupSlugResponseTransformer,
  getApiV1MeResponseTransformer,
  getApiV1MeRsvpsResponseTransformer,
  postApiV1EventsByIdCommentsResponseTransformer,
} from "./transformers.gen";
import type {
  DeleteApiV1EventsByIdCommentsByCommentIdData,
  DeleteApiV1EventsByIdCommentsByCommentIdErrors,
  DeleteApiV1EventsByIdCommentsByCommentIdResponses,
  DeleteApiV1EventsByIdImagesByImageIdData,
  DeleteApiV1EventsByIdImagesByImageIdErrors,
  DeleteApiV1EventsByIdImagesByImageIdResponses,
  DeleteApiV1EventsByIdRsvpData,
  DeleteApiV1EventsByIdRsvpErrors,
  DeleteApiV1EventsByIdRsvpResponses,
  GetApiStatusData,
  GetApiStatusResponses,
  GetApiV1AdminLogsCronByIdData,
  GetApiV1AdminLogsCronByIdErrors,
  GetApiV1AdminLogsCronByIdResponses,
  GetApiV1AdminLogsCronData,
  GetApiV1AdminLogsCronErrors,
  GetApiV1AdminLogsCronResponses,
  GetApiV1AdminLogsSendlogByIdData,
  GetApiV1AdminLogsSendlogByIdErrors,
  GetApiV1AdminLogsSendlogByIdResponses,
  GetApiV1AdminLogsSendlogData,
  GetApiV1AdminLogsSendlogErrors,
  GetApiV1AdminLogsSendlogResponses,
  GetApiV1AdminSecurityIncidentsByIdData,
  GetApiV1AdminSecurityIncidentsByIdErrors,
  GetApiV1AdminSecurityIncidentsByIdResponses,
  GetApiV1AdminSecurityIncidentsData,
  GetApiV1AdminSecurityIncidentsErrors,
  GetApiV1AdminSecurityIncidentsResponses,
  GetApiV1EventsByIdData,
  GetApiV1EventsByIdErrors,
  GetApiV1EventsByIdResponses,
  GetApiV1EventsData,
  GetApiV1EventsResponses,
  GetApiV1GroupsByGroupSlugAdminMembersData,
  GetApiV1GroupsByGroupSlugAdminMembersErrors,
  GetApiV1GroupsByGroupSlugAdminMembersResponses,
  GetApiV1GroupsByGroupSlugAdminSettingsData,
  GetApiV1GroupsByGroupSlugAdminSettingsErrors,
  GetApiV1GroupsByGroupSlugAdminSettingsResponses,
  GetApiV1GroupsByGroupSlugCmsByCmsSlugData,
  GetApiV1GroupsByGroupSlugCmsByCmsSlugErrors,
  GetApiV1GroupsByGroupSlugCmsByCmsSlugResponses,
  GetApiV1GroupsByGroupSlugCmsData,
  GetApiV1GroupsByGroupSlugCmsErrors,
  GetApiV1GroupsByGroupSlugCmsResponses,
  GetApiV1GroupsByGroupSlugData,
  GetApiV1GroupsByGroupSlugErrors,
  GetApiV1GroupsByGroupSlugResponses,
  GetApiV1GroupsData,
  GetApiV1GroupsResponses,
  GetApiV1MeData,
  GetApiV1MeErrors,
  GetApiV1MeResponses,
  GetApiV1MeRsvpsData,
  GetApiV1MeRsvpsErrors,
  GetApiV1MeRsvpsResponses,
  PostApiV1EventsByIdCommentsData,
  PostApiV1EventsByIdCommentsErrors,
  PostApiV1EventsByIdCommentsResponses,
  PostApiV1EventsByIdImagesData,
  PostApiV1EventsByIdImagesErrors,
  PostApiV1EventsByIdImagesResponses,
  PostApiV1EventsByIdRsvpData,
  PostApiV1EventsByIdRsvpErrors,
  PostApiV1EventsByIdRsvpResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health check endpoint
 */
export const getApiStatus = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiStatusData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiStatusResponses, unknown, ThrowOnError>(
    { url: "/api/status", ...options },
  );

/**
 * List recent cron run log entries
 */
export const getApiV1AdminLogsCron = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1AdminLogsCronData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV1AdminLogsCronResponses,
    GetApiV1AdminLogsCronErrors,
    ThrowOnError
  >({
    responseTransformer: getApiV1AdminLogsCronResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/admin/logs/cron",
    ...options,
  });

/**
 * Get a single cron log entry
 */
export const getApiV1AdminLogsCronById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1AdminLogsCronByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV1AdminLogsCronByIdResponses,
    GetApiV1AdminLogsCronByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getApiV1AdminLogsCronByIdResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/admin/logs/cron/{id}",
    ...options,
  });

/**
 * List email send-log entries
 */
export const getApiV1AdminLogsSendlog = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1AdminLogsSendlogData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV1AdminLogsSendlogResponses,
    GetApiV1AdminLogsSendlogErrors,
    ThrowOnError
  >({
    responseTransformer: getApiV1AdminLogsSendlogResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/admin/logs/sendlog",
    ...options,
  });

/**
 * Get a single send-log entry
 */
export const getApiV1AdminLogsSendlogById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV1AdminLogsSendlogByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV1AdminLogsSendlogByIdResponses,
    GetApiV1AdminLogsSendlogByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getApiV1AdminLogsSendlogByIdResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/admin/logs/sendlog/{id}",
    ...options,
  });

/**
 * List recent security incidents
 */
export const getApiV1AdminSecurityIncidents = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetApiV1AdminSecurityIncidentsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV1AdminSecurityIncidentsResponses,
    GetApiV1AdminSecurityIncidentsErrors,
    ThrowOnError
  >({
    responseTransformer: getApiV1AdminSecurityIncidentsResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/admin/security/incidents",
    ...options,
  });

/**
 * Get a single security incident with full provider reports
 */
export const getApiV1AdminSecurityIncidentsById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV1AdminSecurityIncidentsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV1AdminSecurityIncidentsByIdResponses,
    GetApiV1AdminSecurityIncidentsByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getApiV1AdminSecurityIncidentsByIdResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/admin/security/incidents/{id}",
    ...options,
  });

/**
 * List public upcoming events
 */
export const getApiV1Events = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1EventsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV1EventsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getApiV1EventsResponseTransformer,
    url: "/api/v1/events",
    ...options,
  });

/**
 * Get a single event by ID
 */
export const getApiV1EventsById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1EventsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV1EventsByIdResponses,
    GetApiV1EventsByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getApiV1EventsByIdResponseTransformer,
    url: "/api/v1/events/{id}",
    ...options,
  });

/**
 * Post a comment on an event
 */
export const postApiV1EventsByIdComments = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiV1EventsByIdCommentsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiV1EventsByIdCommentsResponses,
    PostApiV1EventsByIdCommentsErrors,
    ThrowOnError
  >({
    responseTransformer: postApiV1EventsByIdCommentsResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/events/{id}/comments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete an event comment (own or admin)
 */
export const deleteApiV1EventsByIdCommentsByCommentId = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteApiV1EventsByIdCommentsByCommentIdData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    DeleteApiV1EventsByIdCommentsByCommentIdResponses,
    DeleteApiV1EventsByIdCommentsByCommentIdErrors,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/events/{id}/comments/{commentId}",
    ...options,
  });

/**
 * Upload an image to an event
 */
export const postApiV1EventsByIdImages = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1EventsByIdImagesData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiV1EventsByIdImagesResponses,
    PostApiV1EventsByIdImagesErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/events/{id}/images",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Delete an event image (own upload or admin)
 */
export const deleteApiV1EventsByIdImagesByImageId = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteApiV1EventsByIdImagesByImageIdData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    DeleteApiV1EventsByIdImagesByImageIdResponses,
    DeleteApiV1EventsByIdImagesByImageIdErrors,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/events/{id}/images/{imageId}",
    ...options,
  });

/**
 * Remove RSVP from an event
 */
export const deleteApiV1EventsByIdRsvp = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteApiV1EventsByIdRsvpData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    DeleteApiV1EventsByIdRsvpResponses,
    DeleteApiV1EventsByIdRsvpErrors,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/events/{id}/rsvp",
    ...options,
  });

/**
 * RSVP yes to an event
 */
export const postApiV1EventsByIdRsvp = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiV1EventsByIdRsvpData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    PostApiV1EventsByIdRsvpResponses,
    PostApiV1EventsByIdRsvpErrors,
    ThrowOnError
  >({
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/events/{id}/rsvp",
    ...options,
  });

/**
 * List active groups
 */
export const getApiV1Groups = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1GroupsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV1GroupsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/groups", ...options });

/**
 * Get a group by slug
 */
export const getApiV1GroupsByGroupSlug = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1GroupsByGroupSlugData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV1GroupsByGroupSlugResponses,
    GetApiV1GroupsByGroupSlugErrors,
    ThrowOnError
  >({
    responseTransformer: getApiV1GroupsByGroupSlugResponseTransformer,
    url: "/api/v1/groups/{groupSlug}",
    ...options,
  });

/**
 * List members of a group
 */
export const getApiV1GroupsByGroupSlugAdminMembers = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV1GroupsByGroupSlugAdminMembersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV1GroupsByGroupSlugAdminMembersResponses,
    GetApiV1GroupsByGroupSlugAdminMembersErrors,
    ThrowOnError
  >({
    responseTransformer:
      getApiV1GroupsByGroupSlugAdminMembersResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/groups/{groupSlug}/admin/members",
    ...options,
  });

/**
 * Read a group settings
 */
export const getApiV1GroupsByGroupSlugAdminSettings = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV1GroupsByGroupSlugAdminSettingsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV1GroupsByGroupSlugAdminSettingsResponses,
    GetApiV1GroupsByGroupSlugAdminSettingsErrors,
    ThrowOnError
  >({
    responseTransformer:
      getApiV1GroupsByGroupSlugAdminSettingsResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/groups/{groupSlug}/admin/settings",
    ...options,
  });

/**
 * List a group's CMS pages
 */
export const getApiV1GroupsByGroupSlugCms = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV1GroupsByGroupSlugCmsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV1GroupsByGroupSlugCmsResponses,
    GetApiV1GroupsByGroupSlugCmsErrors,
    ThrowOnError
  >({ url: "/api/v1/groups/{groupSlug}/cms", ...options });

/**
 * Get a CMS page metadata by group and slug
 */
export const getApiV1GroupsByGroupSlugCmsByCmsSlug = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV1GroupsByGroupSlugCmsByCmsSlugData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiV1GroupsByGroupSlugCmsByCmsSlugResponses,
    GetApiV1GroupsByGroupSlugCmsByCmsSlugErrors,
    ThrowOnError
  >({ url: "/api/v1/groups/{groupSlug}/cms/{cmsSlug}", ...options });

/**
 * Get the authenticated user profile
 */
export const getApiV1Me = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1MeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV1MeResponses,
    GetApiV1MeErrors,
    ThrowOnError
  >({
    responseTransformer: getApiV1MeResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/me",
    ...options,
  });

/**
 * List the authenticated user upcoming RSVPs
 */
export const getApiV1MeRsvps = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1MeRsvpsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiV1MeRsvpsResponses,
    GetApiV1MeRsvpsErrors,
    ThrowOnError
  >({
    responseTransformer: getApiV1MeRsvpsResponseTransformer,
    security: [
      { scheme: "bearer", type: "http" },
      { scheme: "bearer", type: "http" },
    ],
    url: "/api/v1/me/rsvps",
    ...options,
  });
