// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import {
  getApiEventsByIdResponseTransformer,
  getApiEventsResponseTransformer,
} from "./transformers.gen";
import type {
  DeleteApiAuthTokenData,
  DeleteApiAuthTokenResponses,
  DeleteApiCmsByIdBlocksByBlockIdData,
  DeleteApiCmsByIdBlocksByBlockIdResponses,
  DeleteApiCmsByIdData,
  DeleteApiCmsByIdResponses,
  GetApiCmsByIdData,
  GetApiCmsByIdResponses,
  GetApiCmsData,
  GetApiCmsResponses,
  GetApiEventsByIdData,
  GetApiEventsByIdErrors,
  GetApiEventsByIdResponses,
  GetApiEventsData,
  GetApiEventsResponses,
  GetApiGlossaryData,
  GetApiGlossaryResponses,
  GetApiGroupsBySlugData,
  GetApiGroupsBySlugErrors,
  GetApiGroupsBySlugResponses,
  GetApiGroupsData,
  GetApiGroupsErrors,
  GetApiGroupsResponses,
  GetApiLogsActivityData,
  GetApiLogsActivityErrors,
  GetApiLogsActivityResponses,
  GetApiLogsCronData,
  GetApiLogsCronErrors,
  GetApiLogsCronResponses,
  GetApiLogsData,
  GetApiLogsNotFoundData,
  GetApiLogsNotFoundErrors,
  GetApiLogsNotFoundResponses,
  GetApiLogsResponses,
  GetApiLogsSystemData,
  GetApiLogsSystemErrors,
  GetApiLogsSystemResponses,
  GetApiStatusData,
  GetApiStatusResponses,
  GetApiTranslationsData,
  GetApiTranslationsResponses,
  PostApiAuthTokenData,
  PostApiAuthTokenErrors,
  PostApiAuthTokenResponses,
  PostApiCmsByIdBlocksData,
  PostApiCmsByIdBlocksResponses,
  PostApiCmsData,
  PostApiCmsResponses,
  PutApiCmsByIdBlocksByBlockIdData,
  PutApiCmsByIdBlocksByBlockIdResponses,
  PutApiCmsByIdData,
  PutApiCmsByIdResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Revoke current token (requires Bearer)
 */
export const deleteApiAuthToken = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteApiAuthTokenData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    DeleteApiAuthTokenResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/auth/token",
    ...options,
  });

/**
 * Generate Bearer token (email + password)
 */
export const postApiAuthToken = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiAuthTokenResponses,
    PostApiAuthTokenErrors,
    ThrowOnError
  >({
    url: "/api/auth/token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all CMS pages
 */
export const getApiCms = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiCmsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiCmsResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/cms/",
    ...options,
  });

/**
 * Create page
 */
export const postApiCms = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiCmsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<PostApiCmsResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/cms/",
    ...options,
  });

/**
 * Delete page (not allowed if locked)
 */
export const deleteApiCmsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiCmsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiCmsByIdResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/cms/{id}",
    ...options,
  });

/**
 * Get full page with blocks
 */
export const getApiCmsById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiCmsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetApiCmsByIdResponses, unknown, ThrowOnError>(
    {
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/cms/{id}",
      ...options,
    },
  );

/**
 * Update metadata (slug, published, titles, linkNames)
 */
export const putApiCmsById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiCmsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<PutApiCmsByIdResponses, unknown, ThrowOnError>(
    {
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/cms/{id}",
      ...options,
    },
  );

/**
 * Add block
 */
export const postApiCmsByIdBlocks = <ThrowOnError extends boolean = false>(
  options: Options<PostApiCmsByIdBlocksData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiCmsByIdBlocksResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/cms/{id}/blocks",
    ...options,
  });

/**
 * Delete block
 */
export const deleteApiCmsByIdBlocksByBlockId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteApiCmsByIdBlocksByBlockIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiCmsByIdBlocksByBlockIdResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/cms/{id}/blocks/{blockId}",
    ...options,
  });

/**
 * Update block json and/or priority
 */
export const putApiCmsByIdBlocksByBlockId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PutApiCmsByIdBlocksByBlockIdData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    PutApiCmsByIdBlocksByBlockIdResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/cms/{id}/blocks/{blockId}",
    ...options,
  });

/**
 * List upcoming public events (paginated)
 */
export const getApiEvents = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiEventsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiEventsResponses, unknown, ThrowOnError>(
    {
      responseTransformer: getApiEventsResponseTransformer,
      url: "/api/events",
      ...options,
    },
  );

/**
 * Single event detail
 */
export const getApiEventsById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiEventsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiEventsByIdResponses,
    GetApiEventsByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getApiEventsByIdResponseTransformer,
    url: "/api/events/{id}",
    ...options,
  });

/**
 * Glossary data
 */
export const getApiGlossary = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiGlossaryData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiGlossaryResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/glossary", ...options });

/**
 * List public groups (multisite plugin only)
 */
export const getApiGroups = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiGroupsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiGroupsResponses,
    GetApiGroupsErrors,
    ThrowOnError
  >({ url: "/api/groups", ...options });

/**
 * Single group detail
 */
export const getApiGroupsBySlug = <ThrowOnError extends boolean = false>(
  options: Options<GetApiGroupsBySlugData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetApiGroupsBySlugResponses,
    GetApiGroupsBySlugErrors,
    ThrowOnError
  >({ url: "/api/groups/{slug}", ...options });

/**
 * Summary of all log streams (counts + latest timestamps)
 */
export const getApiLogs = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiLogsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiLogsResponses, unknown, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/logs",
    ...options,
  });

/**
 * Recent user activity stream entries
 */
export const getApiLogsActivity = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiLogsActivityData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiLogsActivityResponses,
    GetApiLogsActivityErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/logs/activity",
    ...options,
  });

/**
 * Recent cron run log entries
 */
export const getApiLogsCron = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiLogsCronData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiLogsCronResponses,
    GetApiLogsCronErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/logs/cron",
    ...options,
  });

/**
 * Recent 404 not-found URL log entries
 */
export const getApiLogsNotFound = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiLogsNotFoundData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiLogsNotFoundResponses,
    GetApiLogsNotFoundErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/logs/not-found",
    ...options,
  });

/**
 * Recent file-based system log entries (Monolog rotating file)
 */
export const getApiLogsSystem = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiLogsSystemData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiLogsSystemResponses,
    GetApiLogsSystemErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/logs/system",
    ...options,
  });

/**
 * Service health check
 */
export const getApiStatus = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiStatusData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetApiStatusResponses, unknown, ThrowOnError>(
    { url: "/api/status", ...options },
  );

/**
 * Translation strings
 */
export const getApiTranslations = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiTranslationsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiTranslationsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/translations", ...options });
