// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetApiEventsByIdResponse,
  GetApiEventsResponse,
} from "./types.gen";

const eventSummarySchemaResponseTransformer = (data: any) => {
  if (data.end) {
    data.end = new Date(data.end);
  }
  if (data.start) {
    data.start = new Date(data.start);
  }
  return data;
};

export const getApiEventsResponseTransformer = async (
  data: any,
): Promise<GetApiEventsResponse> => {
  if (data.items) {
    data.items = data.items.map((item: any) =>
      eventSummarySchemaResponseTransformer(item),
    );
  }
  return data;
};

const eventDetailSchemaResponseTransformer = (data: any) => {
  data = eventSummarySchemaResponseTransformer(data);
  return data;
};

export const getApiEventsByIdResponseTransformer = async (
  data: any,
): Promise<GetApiEventsByIdResponse> => {
  data = eventDetailSchemaResponseTransformer(data);
  return data;
};
