// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetApiV1AdminLogsCronByIdResponse,
  GetApiV1AdminLogsCronResponse,
  GetApiV1AdminLogsSendlogByIdResponse,
  GetApiV1AdminLogsSendlogResponse,
  GetApiV1AdminSecurityIncidentsByIdResponse,
  GetApiV1AdminSecurityIncidentsResponse,
  GetApiV1EventsByIdResponse,
  GetApiV1EventsResponse,
  GetApiV1GroupsByGroupSlugAdminMembersResponse,
  GetApiV1GroupsByGroupSlugAdminSettingsResponse,
  GetApiV1GroupsByGroupSlugResponse,
  GetApiV1MeResponse,
  GetApiV1MeRsvpsResponse,
  PostApiV1EventsByIdCommentsResponse,
} from "./types.gen";

const cronLogSummarySchemaResponseTransformer = (data: any) => {
  data.runAt = new Date(data.runAt);
  return data;
};

const cronLogListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    cronLogSummarySchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1AdminLogsCronResponseTransformer = async (
  data: any,
): Promise<GetApiV1AdminLogsCronResponse> => {
  data = cronLogListSchemaResponseTransformer(data);
  return data;
};

const cronLogDetailSchemaResponseTransformer = (data: any) => {
  data = cronLogSummarySchemaResponseTransformer(data);
  return data;
};

export const getApiV1AdminLogsCronByIdResponseTransformer = async (
  data: any,
): Promise<GetApiV1AdminLogsCronByIdResponse> => {
  data = cronLogDetailSchemaResponseTransformer(data);
  return data;
};

const sendlogSummarySchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  return data;
};

const sendlogListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    sendlogSummarySchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1AdminLogsSendlogResponseTransformer = async (
  data: any,
): Promise<GetApiV1AdminLogsSendlogResponse> => {
  data = sendlogListSchemaResponseTransformer(data);
  return data;
};

const sendlogDetailSchemaResponseTransformer = (data: any) => {
  data = sendlogSummarySchemaResponseTransformer(data);
  if (data.providerDispatchedAt) {
    data.providerDispatchedAt = new Date(data.providerDispatchedAt);
  }
  return data;
};

export const getApiV1AdminLogsSendlogByIdResponseTransformer = async (
  data: any,
): Promise<GetApiV1AdminLogsSendlogByIdResponse> => {
  data = sendlogDetailSchemaResponseTransformer(data);
  return data;
};

const incidentSummarySchemaResponseTransformer = (data: any) => {
  data.endedAt = new Date(data.endedAt);
  data.startedAt = new Date(data.startedAt);
  return data;
};

const incidentListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    incidentSummarySchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1AdminSecurityIncidentsResponseTransformer = async (
  data: any,
): Promise<GetApiV1AdminSecurityIncidentsResponse> => {
  data = incidentListSchemaResponseTransformer(data);
  return data;
};

const incidentDetailSchemaResponseTransformer = (data: any) => {
  data = incidentSummarySchemaResponseTransformer(data);
  return data;
};

export const getApiV1AdminSecurityIncidentsByIdResponseTransformer = async (
  data: any,
): Promise<GetApiV1AdminSecurityIncidentsByIdResponse> => {
  data = incidentDetailSchemaResponseTransformer(data);
  return data;
};

const eventSummarySchemaResponseTransformer = (data: any) => {
  data.start = new Date(data.start);
  if (data.stop) {
    data.stop = new Date(data.stop);
  }
  return data;
};

const eventListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    eventSummarySchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1EventsResponseTransformer = async (
  data: any,
): Promise<GetApiV1EventsResponse> => {
  data = eventListSchemaResponseTransformer(data);
  return data;
};

const eventDetailSchemaResponseTransformer = (data: any) => {
  data = eventSummarySchemaResponseTransformer(data);
  return data;
};

export const getApiV1EventsByIdResponseTransformer = async (
  data: any,
): Promise<GetApiV1EventsByIdResponse> => {
  data = eventDetailSchemaResponseTransformer(data);
  return data;
};

const commentCreatedSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  return data;
};

export const postApiV1EventsByIdCommentsResponseTransformer = async (
  data: any,
): Promise<PostApiV1EventsByIdCommentsResponse> => {
  data = commentCreatedSchemaResponseTransformer(data);
  return data;
};

const groupDetailSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  return data;
};

export const getApiV1GroupsByGroupSlugResponseTransformer = async (
  data: any,
): Promise<GetApiV1GroupsByGroupSlugResponse> => {
  data = groupDetailSchemaResponseTransformer(data);
  return data;
};

const groupMemberSchemaResponseTransformer = (data: any) => {
  if (data.joinedAt) {
    data.joinedAt = new Date(data.joinedAt);
  }
  return data;
};

const groupMemberListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    groupMemberSchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1GroupsByGroupSlugAdminMembersResponseTransformer = async (
  data: any,
): Promise<GetApiV1GroupsByGroupSlugAdminMembersResponse> => {
  data = groupMemberListSchemaResponseTransformer(data);
  return data;
};

const groupSettingsSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  return data;
};

export const getApiV1GroupsByGroupSlugAdminSettingsResponseTransformer = async (
  data: any,
): Promise<GetApiV1GroupsByGroupSlugAdminSettingsResponse> => {
  data = groupSettingsSchemaResponseTransformer(data);
  return data;
};

const meProfileSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  return data;
};

export const getApiV1MeResponseTransformer = async (
  data: any,
): Promise<GetApiV1MeResponse> => {
  data = meProfileSchemaResponseTransformer(data);
  return data;
};

const meRsvpListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    eventSummarySchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1MeRsvpsResponseTransformer = async (
  data: any,
): Promise<GetApiV1MeRsvpsResponse> => {
  data = meRsvpListSchemaResponseTransformer(data);
  return data;
};
