// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetApiV1EventsByIdCommentsResponse,
  GetApiV1EventsByIdOccurrencesResponse,
  GetApiV1EventsByIdResponse,
  GetApiV1EventsResponse,
  GetApiV1GroupsByGroupSlugAdminMembersResponse,
  GetApiV1GroupsByGroupSlugAdminSettingsResponse,
  GetApiV1GroupsByGroupSlugResponse,
  GetApiV1LogsCronByIdResponse,
  GetApiV1LogsCronResponse,
  GetApiV1LogsSendlogByIdResponse,
  GetApiV1LogsSendlogResponse,
  GetApiV1MeEventsResponse,
  GetApiV1MeGroupsResponse,
  GetApiV1MembershipsInvitationsResponse,
  GetApiV1MeResponse,
  GetApiV1MeRsvpsResponse,
  GetApiV1SecurityIncidentsByIdResponse,
  GetApiV1SecurityIncidentsResponse,
  PatchApiV1MeResponse,
  PostApiV1EventsByIdCommentsResponse,
  PostApiV1MeAvatarResponse,
  PostApiV1MembershipsGroupsBySlugResponse,
  PostApiV1MembershipsInvitationsByIdAcceptResponse,
} from "./types.gen";

const eventSummarySchemaResponseTransformer = (data: any) => {
  data.start = new Date(data.start);
  if (data.stop) {
    data.stop = new Date(data.stop);
  }
  return data;
};

const eventListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    eventSummarySchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1EventsResponseTransformer = async (
  data: any,
): Promise<GetApiV1EventsResponse> => {
  data = eventListSchemaResponseTransformer(data);
  return data;
};

const eventDetailSchemaResponseTransformer = (data: any) => {
  data.start = new Date(data.start);
  if (data.stop) {
    data.stop = new Date(data.stop);
  }
  return data;
};

export const getApiV1EventsByIdResponseTransformer = async (
  data: any,
): Promise<GetApiV1EventsByIdResponse> => {
  data = eventDetailSchemaResponseTransformer(data);
  return data;
};

const eventCommentSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  return data;
};

const commentListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    eventCommentSchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1EventsByIdCommentsResponseTransformer = async (
  data: any,
): Promise<GetApiV1EventsByIdCommentsResponse> => {
  data = commentListSchemaResponseTransformer(data);
  return data;
};

const commentCreatedSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  return data;
};

export const postApiV1EventsByIdCommentsResponseTransformer = async (
  data: any,
): Promise<PostApiV1EventsByIdCommentsResponse> => {
  data = commentCreatedSchemaResponseTransformer(data);
  return data;
};

export const getApiV1EventsByIdOccurrencesResponseTransformer = async (
  data: any,
): Promise<GetApiV1EventsByIdOccurrencesResponse> => {
  data = eventListSchemaResponseTransformer(data);
  return data;
};

const groupDetailSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  return data;
};

export const getApiV1GroupsByGroupSlugResponseTransformer = async (
  data: any,
): Promise<GetApiV1GroupsByGroupSlugResponse> => {
  data = groupDetailSchemaResponseTransformer(data);
  return data;
};

const groupMemberSchemaResponseTransformer = (data: any) => {
  if (data.joinedAt) {
    data.joinedAt = new Date(data.joinedAt);
  }
  return data;
};

const groupMemberListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    groupMemberSchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1GroupsByGroupSlugAdminMembersResponseTransformer = async (
  data: any,
): Promise<GetApiV1GroupsByGroupSlugAdminMembersResponse> => {
  data = groupMemberListSchemaResponseTransformer(data);
  return data;
};

const groupSettingsSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  return data;
};

export const getApiV1GroupsByGroupSlugAdminSettingsResponseTransformer = async (
  data: any,
): Promise<GetApiV1GroupsByGroupSlugAdminSettingsResponse> => {
  data = groupSettingsSchemaResponseTransformer(data);
  return data;
};

const cronLogSummarySchemaResponseTransformer = (data: any) => {
  data.runAt = new Date(data.runAt);
  return data;
};

const cronLogListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    cronLogSummarySchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1LogsCronResponseTransformer = async (
  data: any,
): Promise<GetApiV1LogsCronResponse> => {
  data = cronLogListSchemaResponseTransformer(data);
  return data;
};

const cronLogDetailSchemaResponseTransformer = (data: any) => {
  data.runAt = new Date(data.runAt);
  return data;
};

export const getApiV1LogsCronByIdResponseTransformer = async (
  data: any,
): Promise<GetApiV1LogsCronByIdResponse> => {
  data = cronLogDetailSchemaResponseTransformer(data);
  return data;
};

const sendlogSummarySchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  return data;
};

const sendlogListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    sendlogSummarySchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1LogsSendlogResponseTransformer = async (
  data: any,
): Promise<GetApiV1LogsSendlogResponse> => {
  data = sendlogListSchemaResponseTransformer(data);
  return data;
};

const sendlogDetailSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  if (data.providerDispatchedAt) {
    data.providerDispatchedAt = new Date(data.providerDispatchedAt);
  }
  return data;
};

export const getApiV1LogsSendlogByIdResponseTransformer = async (
  data: any,
): Promise<GetApiV1LogsSendlogByIdResponse> => {
  data = sendlogDetailSchemaResponseTransformer(data);
  return data;
};

const meProfileSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  return data;
};

export const getApiV1MeResponseTransformer = async (
  data: any,
): Promise<GetApiV1MeResponse> => {
  data = meProfileSchemaResponseTransformer(data);
  return data;
};

export const patchApiV1MeResponseTransformer = async (
  data: any,
): Promise<PatchApiV1MeResponse> => {
  data = meProfileSchemaResponseTransformer(data);
  return data;
};

export const postApiV1MeAvatarResponseTransformer = async (
  data: any,
): Promise<PostApiV1MeAvatarResponse> => {
  data = meProfileSchemaResponseTransformer(data);
  return data;
};

export const getApiV1MeEventsResponseTransformer = async (
  data: any,
): Promise<GetApiV1MeEventsResponse> => {
  data = eventListSchemaResponseTransformer(data);
  return data;
};

const membershipSchemaResponseTransformer = (data: any) => {
  if (data.joinedAt) {
    data.joinedAt = new Date(data.joinedAt);
  }
  return data;
};

const membershipListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    membershipSchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1MeGroupsResponseTransformer = async (
  data: any,
): Promise<GetApiV1MeGroupsResponse> => {
  data = membershipListSchemaResponseTransformer(data);
  return data;
};

const meRsvpListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    eventSummarySchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1MeRsvpsResponseTransformer = async (
  data: any,
): Promise<GetApiV1MeRsvpsResponse> => {
  data = meRsvpListSchemaResponseTransformer(data);
  return data;
};

export const postApiV1MembershipsGroupsBySlugResponseTransformer = async (
  data: any,
): Promise<PostApiV1MembershipsGroupsBySlugResponse> => {
  data = membershipSchemaResponseTransformer(data);
  return data;
};

const invitationSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  if (data.expiresAt) {
    data.expiresAt = new Date(data.expiresAt);
  }
  return data;
};

const invitationListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    invitationSchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1MembershipsInvitationsResponseTransformer = async (
  data: any,
): Promise<GetApiV1MembershipsInvitationsResponse> => {
  data = invitationListSchemaResponseTransformer(data);
  return data;
};

export const postApiV1MembershipsInvitationsByIdAcceptResponseTransformer =
  async (
    data: any,
  ): Promise<PostApiV1MembershipsInvitationsByIdAcceptResponse> => {
    data = membershipSchemaResponseTransformer(data);
    return data;
  };

const incidentSummarySchemaResponseTransformer = (data: any) => {
  data.endedAt = new Date(data.endedAt);
  data.startedAt = new Date(data.startedAt);
  return data;
};

const incidentListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    incidentSummarySchemaResponseTransformer(item),
  );
  return data;
};

export const getApiV1SecurityIncidentsResponseTransformer = async (
  data: any,
): Promise<GetApiV1SecurityIncidentsResponse> => {
  data = incidentListSchemaResponseTransformer(data);
  return data;
};

const incidentDetailSchemaResponseTransformer = (data: any) => {
  data.endedAt = new Date(data.endedAt);
  data.startedAt = new Date(data.startedAt);
  return data;
};

export const getApiV1SecurityIncidentsByIdResponseTransformer = async (
  data: any,
): Promise<GetApiV1SecurityIncidentsByIdResponse> => {
  data = incidentDetailSchemaResponseTransformer(data);
  return data;
};
