// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type GetApiStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/status";
};

export type GetApiStatusResponses = {
  /**
   * Service is healthy
   */
  200: unknown;
};

export type GetApiV1AdminLogsCronData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
  };
  url: "/api/v1/admin/logs/cron";
};

export type GetApiV1AdminLogsCronErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Insufficient role
   */
  403: unknown;
};

export type GetApiV1AdminLogsCronResponses = {
  /**
   * Paginated cron log list
   */
  200: unknown;
};

export type GetApiV1AdminLogsCronByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/v1/admin/logs/cron/{id}";
};

export type GetApiV1AdminLogsCronByIdErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Insufficient role
   */
  403: unknown;
  /**
   * Cron log not found
   */
  404: unknown;
};

export type GetApiV1AdminLogsCronByIdResponses = {
  /**
   * Cron log detail
   */
  200: unknown;
};

export type GetApiV1AdminLogsSendlogData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
  };
  url: "/api/v1/admin/logs/sendlog";
};

export type GetApiV1AdminLogsSendlogErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Insufficient role
   */
  403: unknown;
};

export type GetApiV1AdminLogsSendlogResponses = {
  /**
   * Paginated sendlog list
   */
  200: unknown;
};

export type GetApiV1AdminLogsSendlogByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/v1/admin/logs/sendlog/{id}";
};

export type GetApiV1AdminLogsSendlogByIdErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Insufficient role
   */
  403: unknown;
  /**
   * Sendlog entry not found
   */
  404: unknown;
};

export type GetApiV1AdminLogsSendlogByIdResponses = {
  /**
   * Sendlog detail
   */
  200: unknown;
};

export type GetApiV1AdminSecurityIncidentsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    /**
     * ISO-8601 datetime lower bound on endedAt
     */
    since?: Date;
  };
  url: "/api/v1/admin/security/incidents";
};

export type GetApiV1AdminSecurityIncidentsErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Insufficient role
   */
  403: unknown;
};

export type GetApiV1AdminSecurityIncidentsResponses = {
  /**
   * Incident list
   */
  200: unknown;
};

export type GetApiV1AdminSecurityIncidentsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/v1/admin/security/incidents/{id}";
};

export type GetApiV1AdminSecurityIncidentsByIdErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Insufficient role
   */
  403: unknown;
  /**
   * Incident not found
   */
  404: unknown;
};

export type GetApiV1AdminSecurityIncidentsByIdResponses = {
  /**
   * Incident detail
   */
  200: unknown;
};

export type GetApiV1EventsData = {
  body?: never;
  path?: never;
  query?: {
    locale?: string;
    /**
     * ISO-8601 lower bound (default: now)
     */
    from?: Date;
    /**
     * ISO-8601 upper bound
     */
    to?: Date;
    limit?: number;
    offset?: number;
  };
  url: "/api/v1/events";
};

export type GetApiV1EventsResponses = {
  /**
   * Paginated event list
   */
  200: unknown;
};

export type GetApiV1EventsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: {
    locale?: string;
  };
  url: "/api/v1/events/{id}";
};

export type GetApiV1EventsByIdErrors = {
  /**
   * Event not found or not visible in current context
   */
  404: unknown;
};

export type GetApiV1EventsByIdResponses = {
  /**
   * Event detail
   */
  200: unknown;
};

export type PostApiV1EventsByIdCommentsData = {
  body: {
    content?: string;
  };
  path?: never;
  query?: never;
  url: "/api/v1/events/{id}/comments";
};

export type PostApiV1EventsByIdCommentsErrors = {
  /**
   * Empty content
   */
  400: unknown;
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
  /**
   * Not allowed
   */
  403: unknown;
  /**
   * Event not found
   */
  404: unknown;
};

export type PostApiV1EventsByIdCommentsResponses = {
  /**
   * Comment created
   */
  201: unknown;
};

export type DeleteApiV1EventsByIdCommentsByCommentIdData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/events/{id}/comments/{commentId}";
};

export type DeleteApiV1EventsByIdCommentsByCommentIdErrors = {
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
  /**
   * Not your comment and not admin
   */
  403: unknown;
  /**
   * Comment or event not found
   */
  404: unknown;
};

export type DeleteApiV1EventsByIdCommentsByCommentIdResponses = {
  /**
   * Comment deleted
   */
  204: void;
};

export type DeleteApiV1EventsByIdCommentsByCommentIdResponse =
  DeleteApiV1EventsByIdCommentsByCommentIdResponses[keyof DeleteApiV1EventsByIdCommentsByCommentIdResponses];

export type PostApiV1EventsByIdImagesData = {
  body: {
    file?: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/api/v1/events/{id}/images";
};

export type PostApiV1EventsByIdImagesErrors = {
  /**
   * No file or unsupported format
   */
  400: unknown;
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
  /**
   * Not allowed
   */
  403: unknown;
  /**
   * Event not found
   */
  404: unknown;
};

export type PostApiV1EventsByIdImagesResponses = {
  /**
   * Image uploaded
   */
  201: unknown;
};

export type DeleteApiV1EventsByIdImagesByImageIdData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/events/{id}/images/{imageId}";
};

export type DeleteApiV1EventsByIdImagesByImageIdErrors = {
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
  /**
   * Not your image and not admin
   */
  403: unknown;
  /**
   * Image or event not found
   */
  404: unknown;
};

export type DeleteApiV1EventsByIdImagesByImageIdResponses = {
  /**
   * Image deleted
   */
  204: void;
};

export type DeleteApiV1EventsByIdImagesByImageIdResponse =
  DeleteApiV1EventsByIdImagesByImageIdResponses[keyof DeleteApiV1EventsByIdImagesByImageIdResponses];

export type DeleteApiV1EventsByIdRsvpData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/events/{id}/rsvp";
};

export type DeleteApiV1EventsByIdRsvpErrors = {
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
  /**
   * Not allowed
   */
  403: unknown;
  /**
   * Event not found
   */
  404: unknown;
  /**
   * Event canceled or already started
   */
  409: unknown;
};

export type DeleteApiV1EventsByIdRsvpResponses = {
  /**
   * RSVP removed (or already absent)
   */
  200: unknown;
};

export type PostApiV1EventsByIdRsvpData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/events/{id}/rsvp";
};

export type PostApiV1EventsByIdRsvpErrors = {
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
  /**
   * Not allowed (group membership / blocked)
   */
  403: unknown;
  /**
   * Event not found
   */
  404: unknown;
  /**
   * Event canceled or already started
   */
  409: unknown;
};

export type PostApiV1EventsByIdRsvpResponses = {
  /**
   * RSVP added (or already present)
   */
  200: unknown;
};

export type GetApiV1GroupsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/groups";
};

export type GetApiV1GroupsResponses = {
  /**
   * Array of group summaries
   */
  200: unknown;
};

export type GetApiV1GroupsByGroupSlugData = {
  body?: never;
  path: {
    groupSlug: string;
  };
  query?: never;
  url: "/api/v1/groups/{groupSlug}";
};

export type GetApiV1GroupsByGroupSlugErrors = {
  /**
   * Group not found
   */
  404: unknown;
};

export type GetApiV1GroupsByGroupSlugResponses = {
  /**
   * Group detail
   */
  200: unknown;
};

export type GetApiV1GroupsByGroupSlugAdminMembersData = {
  body?: never;
  path: {
    groupSlug: string;
  };
  query?: never;
  url: "/api/v1/groups/{groupSlug}/admin/members";
};

export type GetApiV1GroupsByGroupSlugAdminMembersErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Caller is not Owner/Organizer of this group
   */
  403: unknown;
  /**
   * Group not found
   */
  404: unknown;
};

export type GetApiV1GroupsByGroupSlugAdminMembersResponses = {
  /**
   * Members list
   */
  200: unknown;
};

export type GetApiV1GroupsByGroupSlugAdminSettingsData = {
  body?: never;
  path: {
    groupSlug: string;
  };
  query?: never;
  url: "/api/v1/groups/{groupSlug}/admin/settings";
};

export type GetApiV1GroupsByGroupSlugAdminSettingsErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Caller is not Owner/Organizer of this group
   */
  403: unknown;
  /**
   * Group not found
   */
  404: unknown;
};

export type GetApiV1GroupsByGroupSlugAdminSettingsResponses = {
  /**
   * Group settings
   */
  200: unknown;
};

export type GetApiV1GroupsByGroupSlugCmsData = {
  body?: never;
  path: {
    groupSlug: string;
  };
  query?: {
    /**
     * Two-letter language code. If omitted, each item's first available language is used. If given but the page lacks that language, falls back to 'en' (or the first available).
     */
    language?: string;
  };
  url: "/api/v1/groups/{groupSlug}/cms";
};

export type GetApiV1GroupsByGroupSlugCmsErrors = {
  /**
   * Group not found
   */
  404: unknown;
};

export type GetApiV1GroupsByGroupSlugCmsResponses = {
  /**
   * List of CMS pages
   */
  200: unknown;
};

export type GetApiV1GroupsByGroupSlugCmsByCmsSlugData = {
  body?: never;
  path: {
    groupSlug: string;
    cmsSlug: string;
  };
  query?: {
    language?: string;
  };
  url: "/api/v1/groups/{groupSlug}/cms/{cmsSlug}";
};

export type GetApiV1GroupsByGroupSlugCmsByCmsSlugErrors = {
  /**
   * Group not found, or page not found / not visible in this group
   */
  404: unknown;
};

export type GetApiV1GroupsByGroupSlugCmsByCmsSlugResponses = {
  /**
   * CMS page metadata
   */
  200: unknown;
};

export type GetApiV1MeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/me";
};

export type GetApiV1MeErrors = {
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
};

export type GetApiV1MeResponses = {
  /**
   * User profile
   */
  200: unknown;
};

export type GetApiV1MeRsvpsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/me/rsvps";
};

export type GetApiV1MeRsvpsErrors = {
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
};

export type GetApiV1MeRsvpsResponses = {
  /**
   * Array of upcoming events the user has RSVPed to
   */
  200: unknown;
};
