// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type CmsPage = {
  languages: Array<string>;
  linkName: string;
  slug: string;
  title: string;
  webUrl: string;
};

export type CmsPageList = {
  items: Array<CmsPage>;
  total: number;
};

export type CommentCreated = {
  content: string;
  createdAt?: Date | null;
  id: number;
};

export type CronLogDetail = CronLogSummary & {
  tasks?: Array<{
    [key: string]: unknown;
  }>;
};

export type CronLogList = {
  items: Array<CronLogSummary>;
  total: number;
};

export type CronLogSummary = {
  durationMs?: number | null;
  id: number;
  runAt: Date;
  status: string;
};

export type ErrorResponse = {
  error: string;
};

export type EventDetail = EventSummary & {
  description?: string | null;
  images?: Array<string>;
  location?: {
    city?: string | null;
    name?: string | null;
    postcode?: string | null;
    street?: string | null;
  } | null;
};

export type EventList = {
  items: Array<EventSummary>;
  limit: number;
  offset: number;
  total: number;
};

export type EventSummary = {
  detailUrl: string;
  id: number;
  previewImageUrl?: string | null;
  rsvpCount: number;
  start: Date;
  stop?: Date | null;
  teaser?: string | null;
  title: string;
  type?: string | null;
  webUrl: string;
};

export type GroupDetail = GroupSummary & {
  createdAt?: Date | null;
  description?: string | null;
  languages?: Array<string>;
  memberCount?: number;
  previewImageUrl?: string | null;
};

export type GroupList = {
  items: Array<GroupSummary>;
  total: number;
};

export type GroupMember = {
  blocked?: boolean;
  email?: string | null;
  id: number;
  joinedAt?: Date | null;
  name?: string | null;
  role?: string | null;
  status: string;
  userId?: number | null;
};

export type GroupMemberList = {
  items: Array<GroupMember>;
  total: number;
};

export type GroupSettings = {
  createdAt?: Date | null;
  description?: string | null;
  id: number;
  name: string;
  slug: string;
  tags?: Array<string>;
  updatedAt?: Date | null;
  visibility?: string | null;
};

export type GroupSummary = {
  detailUrl: string;
  domain?: string | null;
  logoUrl?: string | null;
  name: string;
  slug: string;
  visibility?: string | null;
};

export type HealthStatus = {
  status: string;
};

export type ImageUploaded = {
  id: number;
  url: string;
};

export type IncidentDetail = IncidentSummary & {
  providerReports?: {
    [key: string]: unknown;
  } | null;
  sessionId?: string | null;
  userAgent?: string | null;
};

export type IncidentList = {
  items: Array<IncidentSummary>;
  limit: number;
  total: number;
};

export type IncidentSummary = {
  blockedUntil?: string | null;
  countryCode?: string | null;
  endedAt: Date;
  id: number;
  ip?: string | null;
  severity: string;
  startedAt: Date;
  triggeredBy?: string | null;
};

export type MeProfile = {
  avatarUrl?: string | null;
  bio?: string | null;
  createdAt?: Date | null;
  email: string;
  id: number;
  locale: string;
  name: string;
  role: string;
  status: string;
};

export type MeRsvpList = {
  items: Array<EventSummary>;
  total: number;
};

export type RsvpResult = {
  rsvp: boolean;
  rsvpCount: number;
};

export type SendlogDetail = SendlogSummary & {
  errorMessage?: string | null;
  lang?: string | null;
  providerDispatchedAt?: Date | null;
  sender?: string | null;
};

export type SendlogList = {
  items: Array<SendlogSummary>;
  limit: number;
  total: number;
};

export type SendlogSummary = {
  createdAt?: Date | null;
  id: number;
  recipient: string;
  status: string;
  subject: string;
  template?: string | null;
};

export type GetApiStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/status";
};

export type GetApiStatusResponses = {
  /**
   * Service is healthy
   */
  200: HealthStatus;
};

export type GetApiStatusResponse =
  GetApiStatusResponses[keyof GetApiStatusResponses];

export type GetApiV1AdminLogsCronData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
  };
  url: "/api/v1/admin/logs/cron";
};

export type GetApiV1AdminLogsCronErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Insufficient role
   */
  403: unknown;
};

export type GetApiV1AdminLogsCronResponses = {
  /**
   * Paginated cron log list
   */
  200: CronLogList;
};

export type GetApiV1AdminLogsCronResponse =
  GetApiV1AdminLogsCronResponses[keyof GetApiV1AdminLogsCronResponses];

export type GetApiV1AdminLogsCronByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/v1/admin/logs/cron/{id}";
};

export type GetApiV1AdminLogsCronByIdErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Insufficient role
   */
  403: unknown;
  /**
   * Cron log not found
   */
  404: unknown;
};

export type GetApiV1AdminLogsCronByIdResponses = {
  /**
   * Cron log detail
   */
  200: CronLogDetail;
};

export type GetApiV1AdminLogsCronByIdResponse =
  GetApiV1AdminLogsCronByIdResponses[keyof GetApiV1AdminLogsCronByIdResponses];

export type GetApiV1AdminLogsSendlogData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
  };
  url: "/api/v1/admin/logs/sendlog";
};

export type GetApiV1AdminLogsSendlogErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Insufficient role
   */
  403: unknown;
};

export type GetApiV1AdminLogsSendlogResponses = {
  /**
   * Paginated sendlog list
   */
  200: SendlogList;
};

export type GetApiV1AdminLogsSendlogResponse =
  GetApiV1AdminLogsSendlogResponses[keyof GetApiV1AdminLogsSendlogResponses];

export type GetApiV1AdminLogsSendlogByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/v1/admin/logs/sendlog/{id}";
};

export type GetApiV1AdminLogsSendlogByIdErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Insufficient role
   */
  403: unknown;
  /**
   * Sendlog entry not found
   */
  404: unknown;
};

export type GetApiV1AdminLogsSendlogByIdResponses = {
  /**
   * Sendlog detail
   */
  200: SendlogDetail;
};

export type GetApiV1AdminLogsSendlogByIdResponse =
  GetApiV1AdminLogsSendlogByIdResponses[keyof GetApiV1AdminLogsSendlogByIdResponses];

export type GetApiV1AdminSecurityIncidentsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    /**
     * ISO-8601 datetime lower bound on endedAt
     */
    since?: Date;
  };
  url: "/api/v1/admin/security/incidents";
};

export type GetApiV1AdminSecurityIncidentsErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Insufficient role
   */
  403: unknown;
};

export type GetApiV1AdminSecurityIncidentsResponses = {
  /**
   * Incident list
   */
  200: IncidentList;
};

export type GetApiV1AdminSecurityIncidentsResponse =
  GetApiV1AdminSecurityIncidentsResponses[keyof GetApiV1AdminSecurityIncidentsResponses];

export type GetApiV1AdminSecurityIncidentsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/v1/admin/security/incidents/{id}";
};

export type GetApiV1AdminSecurityIncidentsByIdErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Insufficient role
   */
  403: unknown;
  /**
   * Incident not found
   */
  404: unknown;
};

export type GetApiV1AdminSecurityIncidentsByIdResponses = {
  /**
   * Incident detail
   */
  200: IncidentDetail;
};

export type GetApiV1AdminSecurityIncidentsByIdResponse =
  GetApiV1AdminSecurityIncidentsByIdResponses[keyof GetApiV1AdminSecurityIncidentsByIdResponses];

export type GetApiV1EventsData = {
  body?: never;
  path?: never;
  query?: {
    locale?: string;
    /**
     * ISO-8601 lower bound (default: now)
     */
    from?: Date;
    /**
     * ISO-8601 upper bound
     */
    to?: Date;
    limit?: number;
    offset?: number;
  };
  url: "/api/v1/events";
};

export type GetApiV1EventsResponses = {
  /**
   * Paginated event list
   */
  200: EventList;
};

export type GetApiV1EventsResponse =
  GetApiV1EventsResponses[keyof GetApiV1EventsResponses];

export type GetApiV1EventsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: {
    locale?: string;
  };
  url: "/api/v1/events/{id}";
};

export type GetApiV1EventsByIdErrors = {
  /**
   * Event not found or not visible in current context
   */
  404: ErrorResponse;
};

export type GetApiV1EventsByIdError =
  GetApiV1EventsByIdErrors[keyof GetApiV1EventsByIdErrors];

export type GetApiV1EventsByIdResponses = {
  /**
   * Event detail
   */
  200: EventDetail;
};

export type GetApiV1EventsByIdResponse =
  GetApiV1EventsByIdResponses[keyof GetApiV1EventsByIdResponses];

export type PostApiV1EventsByIdCommentsData = {
  body: {
    content?: string;
  };
  path?: never;
  query?: never;
  url: "/api/v1/events/{id}/comments";
};

export type PostApiV1EventsByIdCommentsErrors = {
  /**
   * Empty content
   */
  400: ErrorResponse;
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
  /**
   * Not allowed
   */
  403: unknown;
  /**
   * Event not found
   */
  404: unknown;
};

export type PostApiV1EventsByIdCommentsError =
  PostApiV1EventsByIdCommentsErrors[keyof PostApiV1EventsByIdCommentsErrors];

export type PostApiV1EventsByIdCommentsResponses = {
  /**
   * Comment created
   */
  201: CommentCreated;
};

export type PostApiV1EventsByIdCommentsResponse =
  PostApiV1EventsByIdCommentsResponses[keyof PostApiV1EventsByIdCommentsResponses];

export type DeleteApiV1EventsByIdCommentsByCommentIdData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/events/{id}/comments/{commentId}";
};

export type DeleteApiV1EventsByIdCommentsByCommentIdErrors = {
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
  /**
   * Not your comment and not admin
   */
  403: unknown;
  /**
   * Comment or event not found
   */
  404: unknown;
};

export type DeleteApiV1EventsByIdCommentsByCommentIdResponses = {
  /**
   * Comment deleted
   */
  204: void;
};

export type DeleteApiV1EventsByIdCommentsByCommentIdResponse =
  DeleteApiV1EventsByIdCommentsByCommentIdResponses[keyof DeleteApiV1EventsByIdCommentsByCommentIdResponses];

export type PostApiV1EventsByIdImagesData = {
  body: {
    file?: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/api/v1/events/{id}/images";
};

export type PostApiV1EventsByIdImagesErrors = {
  /**
   * No file or unsupported format
   */
  400: ErrorResponse;
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
  /**
   * Not allowed
   */
  403: unknown;
  /**
   * Event not found
   */
  404: unknown;
};

export type PostApiV1EventsByIdImagesError =
  PostApiV1EventsByIdImagesErrors[keyof PostApiV1EventsByIdImagesErrors];

export type PostApiV1EventsByIdImagesResponses = {
  /**
   * Image uploaded
   */
  201: ImageUploaded;
};

export type PostApiV1EventsByIdImagesResponse =
  PostApiV1EventsByIdImagesResponses[keyof PostApiV1EventsByIdImagesResponses];

export type DeleteApiV1EventsByIdImagesByImageIdData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/events/{id}/images/{imageId}";
};

export type DeleteApiV1EventsByIdImagesByImageIdErrors = {
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
  /**
   * Not your image and not admin
   */
  403: unknown;
  /**
   * Image or event not found
   */
  404: unknown;
};

export type DeleteApiV1EventsByIdImagesByImageIdResponses = {
  /**
   * Image deleted
   */
  204: void;
};

export type DeleteApiV1EventsByIdImagesByImageIdResponse =
  DeleteApiV1EventsByIdImagesByImageIdResponses[keyof DeleteApiV1EventsByIdImagesByImageIdResponses];

export type DeleteApiV1EventsByIdRsvpData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/events/{id}/rsvp";
};

export type DeleteApiV1EventsByIdRsvpErrors = {
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
  /**
   * Not allowed
   */
  403: unknown;
  /**
   * Event not found
   */
  404: ErrorResponse;
  /**
   * Event canceled or already started
   */
  409: ErrorResponse;
};

export type DeleteApiV1EventsByIdRsvpError =
  DeleteApiV1EventsByIdRsvpErrors[keyof DeleteApiV1EventsByIdRsvpErrors];

export type DeleteApiV1EventsByIdRsvpResponses = {
  /**
   * RSVP removed (or already absent)
   */
  200: RsvpResult;
};

export type DeleteApiV1EventsByIdRsvpResponse =
  DeleteApiV1EventsByIdRsvpResponses[keyof DeleteApiV1EventsByIdRsvpResponses];

export type PostApiV1EventsByIdRsvpData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/events/{id}/rsvp";
};

export type PostApiV1EventsByIdRsvpErrors = {
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
  /**
   * Not allowed (group membership / blocked)
   */
  403: unknown;
  /**
   * Event not found
   */
  404: ErrorResponse;
  /**
   * Event canceled or already started
   */
  409: ErrorResponse;
};

export type PostApiV1EventsByIdRsvpError =
  PostApiV1EventsByIdRsvpErrors[keyof PostApiV1EventsByIdRsvpErrors];

export type PostApiV1EventsByIdRsvpResponses = {
  /**
   * RSVP added (or already present)
   */
  200: RsvpResult;
};

export type PostApiV1EventsByIdRsvpResponse =
  PostApiV1EventsByIdRsvpResponses[keyof PostApiV1EventsByIdRsvpResponses];

export type GetApiV1GroupsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/groups";
};

export type GetApiV1GroupsResponses = {
  /**
   * Array of group summaries
   */
  200: GroupList;
};

export type GetApiV1GroupsResponse =
  GetApiV1GroupsResponses[keyof GetApiV1GroupsResponses];

export type GetApiV1GroupsByGroupSlugData = {
  body?: never;
  path: {
    groupSlug: string;
  };
  query?: never;
  url: "/api/v1/groups/{groupSlug}";
};

export type GetApiV1GroupsByGroupSlugErrors = {
  /**
   * Group not found
   */
  404: ErrorResponse;
};

export type GetApiV1GroupsByGroupSlugError =
  GetApiV1GroupsByGroupSlugErrors[keyof GetApiV1GroupsByGroupSlugErrors];

export type GetApiV1GroupsByGroupSlugResponses = {
  /**
   * Group detail
   */
  200: GroupDetail;
};

export type GetApiV1GroupsByGroupSlugResponse =
  GetApiV1GroupsByGroupSlugResponses[keyof GetApiV1GroupsByGroupSlugResponses];

export type GetApiV1GroupsByGroupSlugAdminMembersData = {
  body?: never;
  path: {
    groupSlug: string;
  };
  query?: never;
  url: "/api/v1/groups/{groupSlug}/admin/members";
};

export type GetApiV1GroupsByGroupSlugAdminMembersErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Caller is not Owner/Organizer of this group
   */
  403: unknown;
  /**
   * Group not found
   */
  404: ErrorResponse;
};

export type GetApiV1GroupsByGroupSlugAdminMembersError =
  GetApiV1GroupsByGroupSlugAdminMembersErrors[keyof GetApiV1GroupsByGroupSlugAdminMembersErrors];

export type GetApiV1GroupsByGroupSlugAdminMembersResponses = {
  /**
   * Members list
   */
  200: GroupMemberList;
};

export type GetApiV1GroupsByGroupSlugAdminMembersResponse =
  GetApiV1GroupsByGroupSlugAdminMembersResponses[keyof GetApiV1GroupsByGroupSlugAdminMembersResponses];

export type GetApiV1GroupsByGroupSlugAdminSettingsData = {
  body?: never;
  path: {
    groupSlug: string;
  };
  query?: never;
  url: "/api/v1/groups/{groupSlug}/admin/settings";
};

export type GetApiV1GroupsByGroupSlugAdminSettingsErrors = {
  /**
   * Missing or invalid bearer token
   */
  401: unknown;
  /**
   * Caller is not Owner/Organizer of this group
   */
  403: unknown;
  /**
   * Group not found
   */
  404: ErrorResponse;
};

export type GetApiV1GroupsByGroupSlugAdminSettingsError =
  GetApiV1GroupsByGroupSlugAdminSettingsErrors[keyof GetApiV1GroupsByGroupSlugAdminSettingsErrors];

export type GetApiV1GroupsByGroupSlugAdminSettingsResponses = {
  /**
   * Group settings
   */
  200: GroupSettings;
};

export type GetApiV1GroupsByGroupSlugAdminSettingsResponse =
  GetApiV1GroupsByGroupSlugAdminSettingsResponses[keyof GetApiV1GroupsByGroupSlugAdminSettingsResponses];

export type GetApiV1GroupsByGroupSlugCmsData = {
  body?: never;
  path: {
    groupSlug: string;
  };
  query?: {
    /**
     * Two-letter language code. If omitted, each item's first available language is used. If given but the page lacks that language, falls back to 'en' (or the first available).
     */
    language?: string;
  };
  url: "/api/v1/groups/{groupSlug}/cms";
};

export type GetApiV1GroupsByGroupSlugCmsErrors = {
  /**
   * Group not found
   */
  404: ErrorResponse;
};

export type GetApiV1GroupsByGroupSlugCmsError =
  GetApiV1GroupsByGroupSlugCmsErrors[keyof GetApiV1GroupsByGroupSlugCmsErrors];

export type GetApiV1GroupsByGroupSlugCmsResponses = {
  /**
   * List of CMS pages
   */
  200: CmsPageList;
};

export type GetApiV1GroupsByGroupSlugCmsResponse =
  GetApiV1GroupsByGroupSlugCmsResponses[keyof GetApiV1GroupsByGroupSlugCmsResponses];

export type GetApiV1GroupsByGroupSlugCmsByCmsSlugData = {
  body?: never;
  path: {
    groupSlug: string;
    cmsSlug: string;
  };
  query?: {
    language?: string;
  };
  url: "/api/v1/groups/{groupSlug}/cms/{cmsSlug}";
};

export type GetApiV1GroupsByGroupSlugCmsByCmsSlugErrors = {
  /**
   * Group not found, or page not found / not visible in this group
   */
  404: ErrorResponse;
};

export type GetApiV1GroupsByGroupSlugCmsByCmsSlugError =
  GetApiV1GroupsByGroupSlugCmsByCmsSlugErrors[keyof GetApiV1GroupsByGroupSlugCmsByCmsSlugErrors];

export type GetApiV1GroupsByGroupSlugCmsByCmsSlugResponses = {
  /**
   * CMS page metadata
   */
  200: CmsPage;
};

export type GetApiV1GroupsByGroupSlugCmsByCmsSlugResponse =
  GetApiV1GroupsByGroupSlugCmsByCmsSlugResponses[keyof GetApiV1GroupsByGroupSlugCmsByCmsSlugResponses];

export type GetApiV1MeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/me";
};

export type GetApiV1MeErrors = {
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
};

export type GetApiV1MeResponses = {
  /**
   * User profile
   */
  200: MeProfile;
};

export type GetApiV1MeResponse = GetApiV1MeResponses[keyof GetApiV1MeResponses];

export type GetApiV1MeRsvpsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/me/rsvps";
};

export type GetApiV1MeRsvpsErrors = {
  /**
   * Missing or invalid Bearer token
   */
  401: unknown;
};

export type GetApiV1MeRsvpsResponses = {
  /**
   * Array of upcoming events the user has RSVPed to
   */
  200: MeRsvpList;
};

export type GetApiV1MeRsvpsResponse =
  GetApiV1MeRsvpsResponses[keyof GetApiV1MeRsvpsResponses];
